name:                DiningPhilosophers
version:             0.1.0.0
github:              "iwashis/DiningPhilosophers"
license:             BSD3
author:              "Tomasz Brengos"
maintainer:          "Tomasz Brengos"
copyright:           "2021 Tomasz Brengos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iwashis/ProFun2021/DiningPhilosophers#readme>

dependencies:
- base >= 4.7 && < 5
- random
- stm
- brick
- vty

library:
  source-dirs: src

executables:
  DiningPhilosophers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiningPhilosophers

tests:
  DiningPhilosophers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiningPhilosophers
